name: Lint PHP files
on: [push, pull_request]

jobs:
  php-74:
    runs-on: ubuntu-latest
    steps:
      - uses: StephaneBour/actions-php-lint@7.4
        with:
          dir: './'

  php-80:
    runs-on: ubuntu-latest
    steps:
      - uses: StephaneBour/actions-php-lint@8.0
        with:
          dir: './'

  php-81:
    runs-on: ubuntu-latest
    steps:
      - uses: StephaneBour/actions-php-lint@8.1
        with:
          dir: './'

  php-82:
    runs-on: ubuntu-latest
    steps:
      - uses: StephaneBour/actions-php-lint@8.1
        with:
          dir: './'
